### ISSUE TITLE
關於程式來源

### ISSUE THREAD

**Issue by HSSLC** [XiangxinKong/manhuagui-downloader#2]
下載器的程式碼是否是從[https://github.com/HSSLC/manhuagui-dlr/](https://github.com/HSSLC/manhuagui-dlr/)複製來的呢？  
**判斷理由：原程式刻意保留的無意義參數與變數命名都相同**  
因為此程式中他人無法突破的關鍵部分皆由HSSLC獨立完成  
如果直接將整段複製走也不標來源是否有點不妥  
  
如果要移植核心部分能否標一下來源

**Comment by XiangxinKong** [comment]
实在是不好意思，是我疏忽了。
我已在readme中和decoder.py的开头添加了作者及出处。

**Comment by XiangxinKong** [comment]
本项目纯粹是拿来玩的，非商业用途。
造成了困扰实在很抱歉。

**Comment by HSSLC** [comment]
非常謝謝。
